"""New Migration

Revision ID: 31f6411c208e
Revises: 7856865218c3
Create Date: 2023-04-13 12:40:53.275543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f6411c208e'
down_revision = '7856865218c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
