"""New Migration

Revision ID: 5e2bd319d8f3
Revises: 31f6411c208e
Create Date: 2023-04-18 11:14:51.317974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2bd319d8f3'
down_revision = '31f6411c208e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('token', sa.Column('time_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'time_update')
    op.drop_column('token', 'time_created')
    # ### end Alembic commands ###
