"""New Migration

Revision ID: 7856865218c3
Revises: 910e12ae9d01
Create Date: 2023-04-13 12:39:10.075757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7856865218c3'
down_revision = '910e12ae9d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'time_created')
    op.drop_column('token', 'time_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('time_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('token', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
