"""New Migration

Revision ID: 94bdc9cdc6db
Revises: dd26838cbb56
Create Date: 2023-03-24 16:29:23.349077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bdc9cdc6db'
down_revision = 'dd26838cbb56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
